package com.lazylee.lzywanandroid.data.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lazylee.lzywanandroid.data.converter.TagConverter;
import java.util.List;

import com.lazylee.lzywanandroid.data.entity.Article;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE".
*/
public class ArticleDao extends AbstractDao<Article, Void> {

    public static final String TABLENAME = "ARTICLE";

    /**
     * Properties of entity Article.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", false, "ID");
        public final static Property ApkLink = new Property(1, String.class, "apkLink", false, "APK_LINK");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property ChapterId = new Property(3, long.class, "chapterId", false, "CHAPTER_ID");
        public final static Property ChapterName = new Property(4, String.class, "chapterName", false, "CHAPTER_NAME");
        public final static Property Collect = new Property(5, boolean.class, "collect", false, "COLLECT");
        public final static Property CourseId = new Property(6, long.class, "courseId", false, "COURSE_ID");
        public final static Property Desc = new Property(7, String.class, "desc", false, "DESC");
        public final static Property EnvelopePic = new Property(8, String.class, "envelopePic", false, "ENVELOPE_PIC");
        public final static Property Fresh = new Property(9, boolean.class, "fresh", false, "FRESH");
        public final static Property Link = new Property(10, String.class, "link", false, "LINK");
        public final static Property NiceDate = new Property(11, String.class, "niceDate", false, "NICE_DATE");
        public final static Property Origin = new Property(12, String.class, "origin", false, "ORIGIN");
        public final static Property ProjectLink = new Property(13, String.class, "projectLink", false, "PROJECT_LINK");
        public final static Property PublishTime = new Property(14, long.class, "publishTime", false, "PUBLISH_TIME");
        public final static Property SuperChapterId = new Property(15, long.class, "superChapterId", false, "SUPER_CHAPTER_ID");
        public final static Property SuperChapterName = new Property(16, String.class, "superChapterName", false, "SUPER_CHAPTER_NAME");
        public final static Property Title = new Property(17, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(18, int.class, "type", false, "TYPE");
        public final static Property Visible = new Property(19, int.class, "visible", false, "VISIBLE");
        public final static Property Zan = new Property(20, int.class, "zan", false, "ZAN");
        public final static Property Tags = new Property(21, String.class, "tags", false, "TAGS");
    }

    private final TagConverter tagsConverter = new TagConverter();

    public ArticleDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE\" (" + //
                "\"ID\" INTEGER NOT NULL ," + // 0: id
                "\"APK_LINK\" TEXT," + // 1: apkLink
                "\"AUTHOR\" TEXT," + // 2: author
                "\"CHAPTER_ID\" INTEGER NOT NULL ," + // 3: chapterId
                "\"CHAPTER_NAME\" TEXT," + // 4: chapterName
                "\"COLLECT\" INTEGER NOT NULL ," + // 5: collect
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 6: courseId
                "\"DESC\" TEXT," + // 7: desc
                "\"ENVELOPE_PIC\" TEXT," + // 8: envelopePic
                "\"FRESH\" INTEGER NOT NULL ," + // 9: fresh
                "\"LINK\" TEXT," + // 10: link
                "\"NICE_DATE\" TEXT," + // 11: niceDate
                "\"ORIGIN\" TEXT," + // 12: origin
                "\"PROJECT_LINK\" TEXT," + // 13: projectLink
                "\"PUBLISH_TIME\" INTEGER NOT NULL ," + // 14: publishTime
                "\"SUPER_CHAPTER_ID\" INTEGER NOT NULL ," + // 15: superChapterId
                "\"SUPER_CHAPTER_NAME\" TEXT," + // 16: superChapterName
                "\"TITLE\" TEXT," + // 17: title
                "\"TYPE\" INTEGER NOT NULL ," + // 18: type
                "\"VISIBLE\" INTEGER NOT NULL ," + // 19: visible
                "\"ZAN\" INTEGER NOT NULL ," + // 20: zan
                "\"TAGS\" TEXT);"); // 21: tags
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Article entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(2, apkLink);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(5, chapterName);
        }
        stmt.bindLong(6, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(7, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(8, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(9, envelopePic);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
        stmt.bindLong(16, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(17, superChapterName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
        stmt.bindLong(19, entity.getType());
        stmt.bindLong(20, entity.getVisible());
        stmt.bindLong(21, entity.getZan());
 
        List tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(22, tagsConverter.convertToDatabaseValue(tags));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Article entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(2, apkLink);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(5, chapterName);
        }
        stmt.bindLong(6, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(7, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(8, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(9, envelopePic);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
        stmt.bindLong(16, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(17, superChapterName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
        stmt.bindLong(19, entity.getType());
        stmt.bindLong(20, entity.getVisible());
        stmt.bindLong(21, entity.getZan());
 
        List tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(22, tagsConverter.convertToDatabaseValue(tags));
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Article readEntity(Cursor cursor, int offset) {
        Article entity = new Article( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // apkLink
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.getLong(offset + 3), // chapterId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // chapterName
            cursor.getShort(offset + 5) != 0, // collect
            cursor.getLong(offset + 6), // courseId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // desc
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // envelopePic
            cursor.getShort(offset + 9) != 0, // fresh
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // link
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // niceDate
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // origin
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // projectLink
            cursor.getLong(offset + 14), // publishTime
            cursor.getLong(offset + 15), // superChapterId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // superChapterName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // title
            cursor.getInt(offset + 18), // type
            cursor.getInt(offset + 19), // visible
            cursor.getInt(offset + 20), // zan
            cursor.isNull(offset + 21) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 21)) // tags
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Article entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setApkLink(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setChapterId(cursor.getLong(offset + 3));
        entity.setChapterName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCollect(cursor.getShort(offset + 5) != 0);
        entity.setCourseId(cursor.getLong(offset + 6));
        entity.setDesc(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEnvelopePic(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFresh(cursor.getShort(offset + 9) != 0);
        entity.setLink(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setNiceDate(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOrigin(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setProjectLink(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPublishTime(cursor.getLong(offset + 14));
        entity.setSuperChapterId(cursor.getLong(offset + 15));
        entity.setSuperChapterName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTitle(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setType(cursor.getInt(offset + 18));
        entity.setVisible(cursor.getInt(offset + 19));
        entity.setZan(cursor.getInt(offset + 20));
        entity.setTags(cursor.isNull(offset + 21) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 21)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Article entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Article entity) {
        return null;
    }

    @Override
    public boolean hasKey(Article entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
