package com.lazylee.lzywanandroid.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lazylee.lzywanandroid.data.entity.Article;
import com.lazylee.lzywanandroid.data.entity.Tag;
import com.lazylee.lzywanandroid.data.entity.HotKey;

import com.lazylee.lzywanandroid.data.greendao.ArticleDao;
import com.lazylee.lzywanandroid.data.greendao.TagDao;
import com.lazylee.lzywanandroid.data.greendao.HotKeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig hotKeyDaoConfig;

    private final ArticleDao articleDao;
    private final TagDao tagDao;
    private final HotKeyDao hotKeyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        hotKeyDaoConfig = daoConfigMap.get(HotKeyDao.class).clone();
        hotKeyDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        hotKeyDao = new HotKeyDao(hotKeyDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Tag.class, tagDao);
        registerDao(HotKey.class, hotKeyDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        tagDaoConfig.clearIdentityScope();
        hotKeyDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public HotKeyDao getHotKeyDao() {
        return hotKeyDao;
    }

}
